-- ⚠️ DO NOT RUN THIS FILE - it was the cause of the Marcas/Retos classification bug.
-- It incorrectly reset all group types to NULL, making groups appear in both tabs.
-- This file is kept only for reference. See supabase_fix_null_types.sql for the fix.
